Design a New York Times Clone
Angelesh1995/New-York-Times pull request #1
Opened 2020-01-30 23:16 UTC by djallas

## Title

Design a clone of New York Clone

2020-01-31 23:38 UTC, fatymahmed requested changes
## Hi @djallas @Angelesh1995 
Your project looks good 👏👏, however, there are a few things that you need to fix.

**Navigation bar**
- [ ]  The NY Times logo should be a link.

**Bottom part**
- [ ] The _More in space and astronomy_ section should contain **links** to other articles with image previews on the leftmost side, kindly change these to links.

**Footer**
- [ ] It should have a fixed position(it sticks to the bottom part of the screen).

**Implementation**
- [ ] You should use `<aside>` tag for Editor's picks section on the rightmost side,  see [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png)

- [ ] Kindly add code linter stickler to your repo, check [this](https://github.com/microverseinc/linters-config/tree/master/css) on how to do it.
- [ ] Your Pull Request should have a short description, see [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png).

[OPTIONAL]
- To easily achieve absolute positioning for the editor's picks and subscribe sections, you can use the `<section>` and `<aside>` tags which help keep the document flow.

2020-01-31 23:40 UTC, fatymahmed requested changes
### Kindly make the suggested changes and request for another code review.
### Status: Changes Required
_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help._

2020-02-03 13:49 UTC, fatymahmed reviewed
## Hi @djallas @Angelesh1995,
Great job on making some of the changes requested, please make all changes for this project to be approved.

**Bottom part**

- The _More in space and astronomy_ section should contain links to other articles with image previews on the leftmost side, kindly change these to links. You've made the title to a link, but each section under this should be a link (the image and the title), I've attached an image that contains marked areas of what I'm specifying in case it's not clear.
![screenshot](https://user-images.githubusercontent.com/16196289/73658218-096e6780-46a5-11ea-8ea1-c9fc09c007dd.png)


-  Your Pull Request should have a short description, see [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png), remove the image and include a short description of the content you have so far.

2020-02-03 13:49 UTC, fatymahmed requested changes
### Kindly make the suggested changes and request for another code review.
### Status: Changes Required
_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help._

2020-02-03 17:19 UTC, nikasulo requested changes
# Really great work @djallas and @Angelesh1995 :rocket: 
Your project looks very neat, your markup is semantic and you have put in a lot of visible work and paid attention to detail :handshake: congrats :medal_military: . 

Did you by any chance get round to seeing the comments @fatymahmed rightfully made about the links in the section for which she attached the screenshot? The small change she suggested hasn't been implemented. Please consider looking into her comments! :100: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-03 17:36 UTC, djallas commented on index.html
> +            </a>
Hello @Oluwadamilareolusakin, I have gotten your feedback mentioning that we should add links in the section. I implemented the feedback @fatymahmed suggested us. Can you kindly take a look on codes I highlighted here? Let us know if we are doing it right or if we are missing something. Thank you

2020-02-03 19:05 UTC, Anna-Myzukina commented
## Hi team!
### Nice job! Project looks! :+1: 

But you still need to fix next:

#### Bottom part

*  It should contain links to other articles with image previews on the leftmost side 



* Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. (Students were asked to use this one, so in most cases their code should be already validated) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
![screen](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png)

![errors](https://user-images.githubusercontent.com/26605804/73682272-bd351e80-46c8-11ea-9229-5b023f0dff22.png)


### Please kindly fix the above issues and send another code review request.
* If you have any questions or need help, you can message me on slack (@ Anna Muzykina). Happy coding

2020-02-03 19:10 UTC, Anna-Myzukina commented on index.html
> +              <div class="text-gray timestamp">Jan. 30</div>
Only content inside tag h5 should be link
Example: <a href="https://www.....">  <h5 class="no-padding no-margin">NASA’s Spitzer Space Telescope Ends 16-Year Mission of Discovery</h5></a>

2020-02-03 19:13 UTC, Anna-Myzukina commented on index.html
> +            <div class="text-gray timestamp">Jan. 29</div>
Only content inside tag h5 should be link

2020-02-03 19:14 UTC, Anna-Myzukina requested changes
The project still needs changes

2020-02-04 15:34 UTC, djallas commented
_**To whom it may concern**_
@Angelesh1995 and I implemented the feedback provided by @fatymahmed and @Anna-Myzukina.
Regarding the feedback on **_`More in space and astronomy`_** section
Links are moved to wrap images(so that they can be clickable) and also inside h5 tags

2020-02-04 21:24 UTC, nikasulo approved these changes
# Congrats! :rocket:
Please merge and keep moving :medal_military: See you at the top!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-04 21:42 UTC, merged